### ISSUE TITLE
Level1Waveblock

### ISSUE THREAD

**Issue by jf2980** [pranavphoenix/WaveMixSR#4]
![image](https://github.com/pranavphoenix/WaveMixSR/assets/22672629/d876955f-d6e4-4a8d-a33b-b008b55c2fd0)

Do you provide so called "Level1Waveblock"? Or it is a function? Please add some comment.

**Comment by pranavphoenix** [comment]
Level1Waveblock comes with the wavemix library. just pip install wavemix

**Comment by pranavphoenix** [comment]
Level1Waveblock comes with the wavemix library. just pip install wavemix

**Comment by jf2980** [comment]
OK thanks

Cloudwalker ***@***.***> 於 2023年8月11日 週五 下午10:59寫道：
